hash-format = "sha256"

[[files]]
file = "mods/3d-placeable-food.pw.toml"
hash = "5ad36f9e39c9e00f7ca29ab78733094388fcbce3a4c59f17ae3df7e8400debf5"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "3fab60aca0fee9153c49b40e1b06b1deebb23800dce7b8b8f471e23f43f3efe5"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "60cd797dfe0cc7a6be4762120a05eed6e7068111b267e4da5993ef2229ce74dc"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "6e39e7712a94830fbc2bd0b6ec73e03f54de5edfcca85da6e89a0021e9a3bf1a"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
hash = "1610d732d574309d48302fc9b3b1ae949ca023daf96658997fa9e83d281bbbd5"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7d1815ec4f2098c4de8b01494373d84da8a5104accd5ae028a2a020595646082"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "b698ef315db976c1f3dea7a1a65fe9b41e6b5f7b84e59e3bd79a25185094ef32"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "5f32244bbf7f4864d6570bde7f7223655f52d5df455e7b9fe650b10dee42f830"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2dda36229536c02155b8bdc705598904b74b3e958e56bf7946785f59c3427a9b"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4f97764f3cb4c74f84afbe32cf8a1d2cefecda129c0f1441906562dcb8f2b8cb"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "31535a06bf76553e83bd982eb3df9158b815cb7d0207a3fc719758d020d683b7"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "3f8fb0012b658c3ed2dfcde1385aa6255ee46cd18b77975d68665aaf0ee2a94d"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "e16d6a33648db866dedba7b9f76698025fb5ae4942bb0ea0ed5761135ed0cb99"
metafile = true

[[files]]
file = "mods/elytra-armor.pw.toml"
hash = "0f6c557bc6342980ff816270a485c2f20edae5b4115c75a1403d81812143ff85"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "f7bb88ccf59b362d533cef59b28b0cab3ef017ad7462dfbe0daae2a0aa30032e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "52eff5c4364676432feed4f4ea8b8a9441d4d95b84d4c434891063c99c05029c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "5f694b0c16bfbf69b05cb28eef7a553ae548e623bc2cbccc98e01d950d3611db"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "80858e1b1477432110b72aab33348635139d6e8fe7bc05db3ba00651de635720"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "e40ab1a8992d800199a6ac5a1a7411bae8141817f645c82c1fdc8c1381393f9e"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "7375f12e54998e218a602ba71a0554dc1bcbd9cc56e152eed4174e86ddecb33c"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "804bd885dd40336596175503d631ab7f529ad12e152872462b1c25f15b2f89bd"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "f48382dc8ad6b473ed5e6d050038513e56697143b1232c1ae8ff40861f06ba2f"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "99deb2f3aa9cd5d7eff3dd58e8acbb32662cbd448a10fd588c166786200e3019"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d9221689ffa47dcd27e6c0590ba7b3227f83d48a6e9592cd09e1835f143d793a"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7fc969e77edc3b0b9946b42070fd858349a74555f0cf9648907241af8a3a2d25"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "acc5199aefdbb418065cf4f3554693fcf9797dc1851a36ca7bad9e660b127763"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "9c7978a3af54d109b1ae4a035672024d178641df8c553126e405f381d814041a"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "3ca867b96ce71321b882606ed97d3c4af8bba5b4886dd71589f29c6e022b152c"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "f013040d2544856ca9f8fe4e07e040aa8a78c87ace3426743a8429d73cba81a3"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "122659d423e8fe5c47b4121bf382e5ceea0ea2c644cd0a08d577cf58ef55d495"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c8bda7e40ba3e14e7e78d1c1f80be842eb6d0acd21fca7b2e6a962bc810b9e46"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "1c1ffc422cf0890d13d1a67f2186e3d65493caef1542376dc53ce45fd442a47d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sound-physics-perfected.pw.toml"
hash = "b9ea052801c503081e138598125402de8b70dcf35627c1ce07ccc82900dc98d0"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "a6fa6d762556487f3ec34b332bbf3e6ad3758d1ecd046026f1a3dfd6f48d17d7"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "2d0ca6e5a2077ae624a65a5310f36ddd6736de699748ac3959022e03844e2f52"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "fb09f6357ae2e3dcfea36520efde6e9b761efffc63b4dfdec5e4b11011bac58c"
metafile = true
