hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "bd0848389894ffe9850efb36210060ff0ac3cc31c74af7f80a897de05df4caa2"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "187b434c519711212abe22449f47b988b7e4110ab4689bd339d40ff8571ab971"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "610076c89a6e55343df37808fcf59806330eb37b4108c5b080807c95cd0c7162"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "a9f6cf1a98bc318c887b672aecaff6ffdbf33a6ec06af5f2686b292988d0846e"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
hash = "5335a88286ee7b6d8461605545211712773523468877c7edd4b04093aa808b78"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "b698ef315db976c1f3dea7a1a65fe9b41e6b5f7b84e59e3bd79a25185094ef32"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "0b775ba140d7797e2456b8b09c7162f6a81de22abb7feb2e8437847cefd86d0a"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "6a492387f6348192bcb9e2ee15f9be142100648ce60080a75f980185cb66ee13"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "252d64d837d274aa46b00729f136d5900a5fb029f8c25f11f280a9b34da6add1"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2dda36229536c02155b8bdc705598904b74b3e958e56bf7946785f59c3427a9b"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d8b2d90b9c5ee1454bde1bd45358e1495e49750ac2ac534ddf745a1ae06d738a"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "41440aa391c6fb6ba275a47a78c4353fb5a2e4a76b2cd8d91e7751c7507a2637"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "219cff1d722d7b7d98380052c8707e7242def480d3e34f571850f1329f45ad12"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "447ec530620e3c0da62316cb3358e43c15132084aab22ba992fefac199ca92a9"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "ecc30c21290ac87a732085e16add94a392d4e5dfc0bae5f353975eea51a38a84"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "f7bb88ccf59b362d533cef59b28b0cab3ef017ad7462dfbe0daae2a0aa30032e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "1fbcec6fae4237b80bf2becfc06fb52a49512821f402b5928b1e2533c73b3142"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "7d61ad815f97afb27f7e97475e80376aa19fecf25a1b04a500a4c3a6e5055973"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "debc633d962665af2873b7e4c74a5bd8da18d6a883971e73b9039f9612f457b7"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "a104f2f6044d43bbc5a5badc6f589b2f6f5a1b9c9e47e00dfbad5061aa3b51f4"
metafile = true

[[files]]
file = "mods/guts.pw.toml"
hash = "3d8eee2308a2bf490e64a2bcf5f1cf085d3e2b6bea8a6d3d5abb71e527c42b70"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "ab5b5ecade1d9cf981d11fee68d5f42e5d933a4e4d9b15b2657d8da2a4f8304a"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "6492b21e2a58e97ab65ff384db18606ce317ea3b78fad7051e6e34899fe8e85b"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "301ccf2d9e570c60a73ba9ff99a89db1b813d8d699040f95ed7a6b75df215089"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "7375f12e54998e218a602ba71a0554dc1bcbd9cc56e152eed4174e86ddecb33c"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "61a29cdfacd6805daf1a1c88347cf096cbb2ae19d6194eec062defe4b0814ca9"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "98a700c8ac406b4035f2f1fe3f6e660ca8b14ab697d8464a3f86d94d87c06f7a"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "38d5a309095c272b7cb305e63bea744ab60052b36bda04051bd48914386ddbf1"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "f48382dc8ad6b473ed5e6d050038513e56697143b1232c1ae8ff40861f06ba2f"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "99deb2f3aa9cd5d7eff3dd58e8acbb32662cbd448a10fd588c166786200e3019"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "4842a349ba8e18407a4e32ef184ad1d2a437ff8e5b0c158391b6225216b4b8ce"
metafile = true

[[files]]
file = "mods/mapfrontiers.pw.toml"
hash = "eb5baa5b120a9105528270d3f39f3d400cc16b5ad59bce4eb1ee9478b158c067"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "14f66aae0008a361a15854905e6ed095086b61e78056819458da8cace6ae8e09"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "819fa1f18729ecf4b95a1ada63d2cabb1a3a53e02f93145432cd80a5baa97048"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "4d0702eaaa585f52e89ee2c58de2e322937f810907aa6a84d9b0267b201e2a25"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "84e110f76128936a4ee4df891fe21e882fc486d14e184af8bdde6b034635b7da"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "122659d423e8fe5c47b4121bf382e5ceea0ea2c644cd0a08d577cf58ef55d495"
metafile = true

[[files]]
file = "mods/purpurpacks-re-dye-glazed-terracotta.pw.toml"
hash = "80d380af94f36b46e2d49ae4b7e345ace4dfeb5cda802f6904b21a1c2716b728"
metafile = true

[[files]]
file = "mods/purpurpacks-re-dye-terracotta.pw.toml"
hash = "0f25c7e3f6200951dc08fb0740b38219b5e3f48147c635cca3ab1386d223ed4d"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "4739fd0f979dd5fefecc5c47a07ef61ca78d1bdf525cd4e544e1a331ede3ca61"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c8bda7e40ba3e14e7e78d1c1f80be842eb6d0acd21fca7b2e6a962bc810b9e46"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cc98ef15cb0fb331703af145ea92255765247a2b1d27b87d05a44ad0dc6d9b4e"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
hash = "391cfcaddc727aca042186688aaa41bafa1666527a36499715e357432304bcf0"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sound-physics-perfected.pw.toml"
hash = "948bdbbaeb8285c2f0a100e99dbbb197b1bdbc1c3115edaac075f95a58114c92"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9bdd041fb29ab003ef5bb1f0ba53516847e32e3010a3fce247f743fc98e08a6b"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "5a639c2db9f85e15aa537de14769f37e0bde34d0c1a31f0fd6e32fd182669bed"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "77a945b5ff32f1a821cd2942bcd2fb411740061f022efad3e48eaa8577b48636"
metafile = true

[[files]]
file = "mods/tradable-potions.pw.toml"
hash = "8ed5fa6bc8bb1af8f0ac522b99599cf084f9733b9bfd456821e247a350b6cc87"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/vegan-ink-sacs.pw.toml"
hash = "28391da2ff8fde46205b7e5bba1ac07fd1509dd8998ecd1d92221a5503e88c71"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "d9b210470eeaca6109002dcc8c1442dbbef5468bbf7be516651e7fc25b3d5c5e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "af20070dd9497817a83162c17b181a0a44f7213ea302d059a81c5aed02d0c877"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2709ce9505c0a00b9406f83eb4bc158f5cad773b96fc3826c88dca45d65876cd"
metafile = true
