hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "a1833660aa682fde7a8f110355138c15e04782f7dc20011f9685eef1bd5c52ae"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "e3ebae83eac15915f4df507a68d875d68367b9d4e1cada82b4fa78c51e001641"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "610076c89a6e55343df37808fcf59806330eb37b4108c5b080807c95cd0c7162"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "6e39e7712a94830fbc2bd0b6ec73e03f54de5edfcca85da6e89a0021e9a3bf1a"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
hash = "1610d732d574309d48302fc9b3b1ae949ca023daf96658997fa9e83d281bbbd5"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "f206935f72461a344b05f85169756337cf2612f69b2f49a63f4108ea823969fb"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "b698ef315db976c1f3dea7a1a65fe9b41e6b5f7b84e59e3bd79a25185094ef32"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "0b775ba140d7797e2456b8b09c7162f6a81de22abb7feb2e8437847cefd86d0a"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "6a492387f6348192bcb9e2ee15f9be142100648ce60080a75f980185cb66ee13"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "252d64d837d274aa46b00729f136d5900a5fb029f8c25f11f280a9b34da6add1"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "10e62eda6080e5ef86cdb707fea882afc798023e928c3eecea54d71ee58abe24"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d8b2d90b9c5ee1454bde1bd45358e1495e49750ac2ac534ddf745a1ae06d738a"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "31535a06bf76553e83bd982eb3df9158b815cb7d0207a3fc719758d020d683b7"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "219cff1d722d7b7d98380052c8707e7242def480d3e34f571850f1329f45ad12"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "447ec530620e3c0da62316cb3358e43c15132084aab22ba992fefac199ca92a9"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "ae499bc61d39d26ec2bbca7ef5f37bf6240a7fdd0729fbc8573acabd6f0e4bc5"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "ecc30c21290ac87a732085e16add94a392d4e5dfc0bae5f353975eea51a38a84"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "fdb984586992e70244d575185580d47a2c73ff6461ec29bcae580ef9b51b8949"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "1fbcec6fae4237b80bf2becfc06fb52a49512821f402b5928b1e2533c73b3142"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "7d61ad815f97afb27f7e97475e80376aa19fecf25a1b04a500a4c3a6e5055973"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "debc633d962665af2873b7e4c74a5bd8da18d6a883971e73b9039f9612f457b7"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "a104f2f6044d43bbc5a5badc6f589b2f6f5a1b9c9e47e00dfbad5061aa3b51f4"
metafile = true

[[files]]
file = "mods/guts.pw.toml"
hash = "3d8eee2308a2bf490e64a2bcf5f1cf085d3e2b6bea8a6d3d5abb71e527c42b70"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "ab5b5ecade1d9cf981d11fee68d5f42e5d933a4e4d9b15b2657d8da2a4f8304a"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "7ce0c6bc41c817996eb8f81d282e2898f3fcd606d8f0ac0c526e8f09735a7b77"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "80858e1b1477432110b72aab33348635139d6e8fe7bc05db3ba00651de635720"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "927ef1db35ff0f514378cb5a9a1d11fa49dc4a6754d50d18445b7174bb325a87"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "7375f12e54998e218a602ba71a0554dc1bcbd9cc56e152eed4174e86ddecb33c"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "61a29cdfacd6805daf1a1c88347cf096cbb2ae19d6194eec062defe4b0814ca9"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "98a700c8ac406b4035f2f1fe3f6e660ca8b14ab697d8464a3f86d94d87c06f7a"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "38d5a309095c272b7cb305e63bea744ab60052b36bda04051bd48914386ddbf1"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "f48382dc8ad6b473ed5e6d050038513e56697143b1232c1ae8ff40861f06ba2f"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "99deb2f3aa9cd5d7eff3dd58e8acbb32662cbd448a10fd588c166786200e3019"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "4842a349ba8e18407a4e32ef184ad1d2a437ff8e5b0c158391b6225216b4b8ce"
metafile = true

[[files]]
file = "mods/mapfrontiers.pw.toml"
hash = "eb5baa5b120a9105528270d3f39f3d400cc16b5ad59bce4eb1ee9478b158c067"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "b237026e1ed2780812c42a4649d7bf4e61d2ec20d09f9677ad8833ac3680a2e5"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "aa04b1125a2c18377d45268ff59eb7784e7a3e5f6ef9aff805ef0a7485d4ca48"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "14f66aae0008a361a15854905e6ed095086b61e78056819458da8cace6ae8e09"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "819fa1f18729ecf4b95a1ada63d2cabb1a3a53e02f93145432cd80a5baa97048"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "4d0702eaaa585f52e89ee2c58de2e322937f810907aa6a84d9b0267b201e2a25"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "84e110f76128936a4ee4df891fe21e882fc486d14e184af8bdde6b034635b7da"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "122659d423e8fe5c47b4121bf382e5ceea0ea2c644cd0a08d577cf58ef55d495"
metafile = true

[[files]]
file = "mods/purpurpacks-re-dye-glazed-terracotta.pw.toml"
hash = "80d380af94f36b46e2d49ae4b7e345ace4dfeb5cda802f6904b21a1c2716b728"
metafile = true

[[files]]
file = "mods/purpurpacks-re-dye-terracotta.pw.toml"
hash = "0f25c7e3f6200951dc08fb0740b38219b5e3f48147c635cca3ab1386d223ed4d"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "4739fd0f979dd5fefecc5c47a07ef61ca78d1bdf525cd4e544e1a331ede3ca61"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c8bda7e40ba3e14e7e78d1c1f80be842eb6d0acd21fca7b2e6a962bc810b9e46"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9c13a5497b1706986d7cedef548ea030e763c4b3029c8cc397cf9b0c0369f204"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
hash = "391cfcaddc727aca042186688aaa41bafa1666527a36499715e357432304bcf0"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sound-physics-perfected.pw.toml"
hash = "a3b657aae0661cabeb3c078f50d17609a0c291eec6d7930cd96b85b8ed96857b"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9bdd041fb29ab003ef5bb1f0ba53516847e32e3010a3fce247f743fc98e08a6b"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "857220cbd9e3ae276ec2a8ec2c6b2e6ee79a53b4727739bec3e42ec1e8f625c2"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "5a639c2db9f85e15aa537de14769f37e0bde34d0c1a31f0fd6e32fd182669bed"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "77a945b5ff32f1a821cd2942bcd2fb411740061f022efad3e48eaa8577b48636"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "d9b210470eeaca6109002dcc8c1442dbbef5468bbf7be516651e7fc25b3d5c5e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "2d0ca6e5a2077ae624a65a5310f36ddd6736de699748ac3959022e03844e2f52"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "728b51ab3caf7aecb6aa9013037a11302a6959faba525435a564041a3bf05cb4"
metafile = true
