name = "CTAF Minecraft Pack"
author = "slimit75"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61e444c53b3dbb805d0e0bae0966c02b686f343e6dda8df0d077081ac7526e45"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
