name = "CTAF Minecraft Pack"
author = "slimit75"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aea758979a7cdd96214ce0f4e171e4bbfce716428eb48ea26cdb1f4bf9242dc"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
