name = "CTAF Minecraft Pack"
author = "slimit75"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf7785af0e1fbaae4e91ed308f14bf99af17af9938ee09f6220cf77716aabaf0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
