name = "CTAF Minecraft Pack"
author = "slimit75"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29203b45f9319181f5e8c6aa5ef394755a2a38af0dcd109f0c4104e0aa14aec8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
